name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Action started"

      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t bbsimon/react-app --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL}}' .
      - name: Push docker image to docker hub
        run: docker push bbsimon/react-app:latest
  deploy:
    needs: build
    runs-on: self-hosted>
    steps:
      - name: Pull docker image from docker hub
        run: docker pull bbsimon/react-app:latest
      - name: Delete running container
        run: docker rm -f react-app-container
      - name: Run docker container
        run: docker run -d -p 3000:80 --name react-app-container bbsimon/react-app
